! app/main.f90
! Using trigonometric functions to generate data that can be plotted.

program main

   implicit none

   ! Set up Double Precision (DP) for higher accuracy
   integer, parameter :: DP = kind(1.0D0)
   ! Define the mathematical constant Pi
   real(DP), parameter :: PI = 4.0_DP*atan(1.0_DP)

   ! Configuration Parameters
   real(DP), parameter :: start_value = 0.0_DP
   real(DP), parameter :: end_value = 2.0_DP*PI
   integer, parameter :: num_points = 100

   ! Data output file name
   character(len=15) :: filename = "sine_data.txt"

   ! Variables
   real(DP) :: x, y
   real(DP) :: step_size
   character(len=100) :: cmd, temp
   integer :: i, status

   ! Calculate the step size between points
   step_size = (end_value - start_value)/real(num_points - 1, DP)

   ! Open the output file
   open (unit=10, file=filename, status='replace')

   ! Calculate and write the points
   do i = 0, num_points - 1
      x = start_value + real(i, DP)*step_size
      y = sin(x)
      ! Save output
      write (10, '(F15.8, 2x, F15.8)') x, y
      ! View output
      print '("(x, y):", F15.8, F15.8)', x, y
   end do

   ! Close the output file
   close (10)

   print '("Data successfully generated in ", A)', filename

   ! Create a command script for Gnuplot.
   open (unit=11, file="plot_commands.gb", status="replace")

   write (11, *) 'set terminal png size 800,600'
   write (11, *) 'set output "sine_plot.png"'
   write (11, *) 'set title "Graph of the Sinusoidal Function Generated by Fortran" font ",14"'
   write (11, *) 'set xlabel "X (Radians)"'
   write (11, *) 'set ylabel "Y (sin(x))"'
   write (11, *) 'set grid'
   write (11, *) 'set xrange [0:7]'
   write (11, *) 'set yrange [-1.2:1.2]'

   temp = 'plot "'//trim(filename)// &
          '" using 1:2 with lines title "sin(x)" linecolor rgb "blue" linewidth 2'

   write (11, *) trim(temp)

   ! Close the output file
   close (11)

   ! Plot
   cmd = trim('gnuplot plot_commands.gb')
   call EXECUTE_COMMAND_LINE(command=cmd, exitstat=status)
   if (status == 0) then
      print '("Plotting completed successfully via gnuplot.")'
   else
      print '("Error executing gnuplot (Status:", A)', status
   end if

end program main
